"use server";

/**
 * Server-side sync target for stock counts. Client components go through
 * lib/offline/inventory.ts's Dexie-backed layer instead — never this file
 * directly.
 *
 * THE TWO RULES this module exists to honour, both learned the hard way
 * elsewhere in this codebase:
 *
 *   1. Every write takes an id generated by the client when the operation
 *      was queued, and checks for it before creating anything. A queued
 *      write can commit and lose its reply, after which the sync engine
 *      retries for ever; without this, one count would become two sessions
 *      and one correction would be applied twice. This is the same defect
 *      that duplicated delivery receipts.
 *
 *   2. The counted quantity is applied as an absolute value, never as a
 *      delta against current stock. Stock may have moved between the count
 *      and the sync — a sale, a delivery — and adding the gap on top would
 *      land on a figure nobody ever counted. The shelf was counted; that
 *      count is what the stock becomes.
 */

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db/client";
import { Prisma } from "@/lib/db/generated/client";
import { requireUser } from "@/lib/auth/session";
import type { InventorySessionStatus } from "@/lib/offline/db";

export type InventorySessionRecord = {
  id: string;
  statut: InventorySessionStatus;
  dateDebut: Date;
  dateFin: Date | null;
};

export type StartInventoryResult = InventorySessionRecord & {
  /**
   * Products the device holds but the server does not, left out of the
   * server-side session. They stay countable locally; the sync engine
   * records them in the conflict log so the gap is visible.
   */
  skippedProductIds: string[];
};

export type StartInventoryInput = {
  /** Products captured when the session opened, with their frozen stock. */
  lines: Array<{ productId: string; quantiteTheorique: number }>;
  /** When the pharmacist actually started, not when this reached the server. */
  startedAt: string;
};

/**
 * Opens a session and freezes the expected quantity of every product in it.
 *
 * `options.id` is required in practice — the offline layer always supplies
 * it — but kept optional so the signature matches createProduct/createSale.
 */
export async function startInventorySession(
  input: StartInventoryInput,
  options?: { id?: string },
): Promise<StartInventoryResult> {
  const user = await requireUser();

  const existing = options?.id
    ? await prisma.inventorySession.findFirst({
        where: { id: options.id, pharmacyId: user.pharmacyId },
        select: { id: true, statut: true, dateDebut: true, dateFin: true },
      })
    : null;
  if (existing) {
    // A replay of a session that already landed. Returning it unchanged is
    // the whole point: creating a second one would split one physical count
    // across two records.
    return { ...toRecord(existing), skippedProductIds: [] };
  }

  /**
   * The device's product cache can be ahead of the server: a product
   * created offline whose own sync has not landed yet, or one whose sync
   * was abandoned. Those ids have no row in `products`, and inserting a
   * count for them violates the foreign key — which rolls the whole
   * transaction back, leaving no session at all and every queued count
   * afterwards failing with "session introuvable".
   *
   * Observed in real use: a device holding more products than the server
   * could not open a single session. So the lines are filtered to what the
   * server actually knows, and the rest are reported back rather than
   * silently dropped.
   */
  const requestedIds = [...new Set(input.lines.map((line) => line.productId))];
  const knownIds = new Set(
    (
      await prisma.product.findMany({
        where: { id: { in: requestedIds }, pharmacyId: user.pharmacyId },
        select: { id: true },
      })
    ).map((product) => product.id),
  );
  const known = input.lines.filter((line) => knownIds.has(line.productId));
  const skippedProductIds = requestedIds.filter((id) => !knownIds.has(id));

  const session = await prisma.$transaction(async (tx) => {
    const created = await tx.inventorySession.create({
      data: {
        ...(options?.id ? { id: options.id } : {}),
        pharmacyId: user.pharmacyId,
        userId: user.id,
        statut: "EN_COURS",
        dateDebut: new Date(input.startedAt),
      },
      select: { id: true, statut: true, dateDebut: true, dateFin: true },
    });

    if (known.length > 0) {
      await tx.inventoryCount.createMany({
        data: known.map((line) => ({
          sessionId: created.id,
          productId: line.productId,
          quantiteTheorique: line.quantiteTheorique,
        })),
        skipDuplicates: true,
      });
    }

    return created;
  });

  revalidatePath("/inventaire");
  return { ...toRecord(session), skippedProductIds };
}

export type RecordCountInput = {
  sessionId: string;
  productId: string;
  /** Needed only if the line has to be created — see recordInventoryCount. */
  quantiteTheorique: number;
  quantiteComptee: number;
  /** When the shelf was actually counted. */
  countedAt: string;
};

/**
 * Records one product's count.
 *
 * Idempotent by construction rather than by an explicit guard: the
 * `(session_id, product_id)` unique index means a replay updates the same
 * row. Counts are sent one product at a time so a session interrupted
 * halfway still has every shelf already counted safely on the server.
 */
export async function recordInventoryCount(input: RecordCountInput): Promise<void> {
  const user = await requireUser();

  const session = await prisma.inventorySession.findFirst({
    where: { id: input.sessionId, pharmacyId: user.pharmacyId },
    select: { id: true, statut: true },
  });
  if (!session) {
    throw new Error("Session d'inventaire introuvable.");
  }
  if (session.statut === "TERMINE") {
    // The adjustments are already applied; a late count would change a
    // report someone has signed off on.
    throw new Error("Cet inventaire est déjà terminé.");
  }

  const updated = await prisma.inventoryCount.updateMany({
    where: { sessionId: session.id, productId: input.productId },
    data: { quantiteComptee: input.quantiteComptee, dateComptage: new Date(input.countedAt) },
  });
  if (updated.count > 0) return;

  // No line for this product: it was skipped when the session opened
  // because the server did not know the product yet. If its own sync has
  // landed since, the count belongs on the record after all.
  const product = await prisma.product.findFirst({
    where: { id: input.productId, pharmacyId: user.pharmacyId },
    select: { id: true },
  });
  if (!product) {
    // A business refusal, not a transient failure: retrying cannot make a
    // product exist. It lands in the conflict log, where it stays visible.
    throw new Error("Produit introuvable sur le serveur — comptage non enregistré.");
  }

  await prisma.inventoryCount.create({
    data: {
      sessionId: session.id,
      productId: input.productId,
      quantiteTheorique: input.quantiteTheorique,
      quantiteComptee: input.quantiteComptee,
      dateComptage: new Date(input.countedAt),
    },
  });
}

export type ApplyInventoryInput = {
  sessionId: string;
  /** Only products in variance — see lib/inventory/variance.ts. */
  adjustments: Array<{ productId: string; quantiteComptee: number; ecart: number }>;
  /** When the pharmacist applied them, not when this reached the server. */
  appliedAt: string;
};

/**
 * Applies a finished count: each product's stock becomes the counted
 * figure, one stock movement records the correction, and the session
 * closes.
 */
export async function applyInventoryAdjustments(input: ApplyInventoryInput): Promise<void> {
  const user = await requireUser();
  const appliedAt = new Date(input.appliedAt);

  await prisma.$transaction(async (tx) => {
    const session = await tx.inventorySession.findFirst({
      where: { id: input.sessionId, pharmacyId: user.pharmacyId },
      select: { id: true, statut: true },
    });
    if (!session) {
      throw new Error("Session d'inventaire introuvable.");
    }
    // The idempotency guard. A session already closed has had its
    // adjustments applied; replaying would move stock a second time and
    // write a second set of movements.
    if (session.statut === "TERMINE") {
      return;
    }

    /**
     * Everything below is a fixed number of statements, whatever the size
     * of the count.
     *
     * The first version issued three round trips per adjusted product —
     * a read, an update and a movement. On a real inventory that is
     * hundreds of sequential queries over a pooled connection, and it blew
     * past Prisma's 5 s interactive-transaction limit: "A query cannot be
     * executed on an expired transaction... 6584 ms passed". Nothing was
     * applied, and the queued write retried for ever.
     */
    const productIds = input.adjustments.map((adjustment) => adjustment.productId);
    const known = new Set(
      (
        await tx.product.findMany({
          where: { id: { in: productIds }, pharmacyId: user.pharmacyId },
          select: { id: true },
        })
      ).map((product) => product.id),
    );
    // A product the server does not have cannot be adjusted — same reason
    // its line was skipped when the session opened.
    const applicable = input.adjustments.filter((adjustment) => known.has(adjustment.productId));

    if (applicable.length > 0) {
      // Set, not increment — see rule 2 at the top of this file. One
      // statement: the query builder has no bulk update with a different
      // value per row, so the pairs are joined into a VALUES list. Each is
      // cast explicitly, or Postgres cannot infer the type of a bound
      // parameter appearing only inside VALUES.
      await tx.$executeRaw`
        UPDATE products AS p
        SET quantity_in_stock = v.qty
        FROM (VALUES ${Prisma.join(
          applicable.map(
            (adjustment) =>
              Prisma.sql`(${adjustment.productId}::text, ${adjustment.quantiteComptee}::int)`,
          ),
        )}) AS v(id, qty)
        WHERE p.id = v.id AND p.pharmacy_id = ${user.pharmacyId}
      `;

      await tx.stockMovement.createMany({
        data: applicable.map((adjustment) => ({
          pharmacyId: user.pharmacyId,
          productId: adjustment.productId,
          type: adjustment.ecart > 0 ? ("IN" as const) : ("OUT" as const),
          quantity: Math.abs(adjustment.ecart),
          reason: `Ajustement d'inventaire ${session.id}`,
          createdAt: appliedAt,
        })),
      });

      // TODO(event-log): there is no `event_log` table in this project yet
      // — verified against prisma/schema.prisma at the time of writing, no
      // model or migration defines one. When it is added, log one entry per
      // adjustment HERE (server-side; the table has no offline counterpart)
      // and stamp it with `appliedAt`, the moment the pharmacist applied
      // the correction on the device, never `new Date()`. A count applied
      // in a stockroom on Monday and synced on Tuesday belongs to Monday.
    }

    await tx.inventorySession.update({
      where: { id: session.id },
      data: { statut: "TERMINE", dateFin: appliedAt },
    });
  });

  revalidatePath("/inventaire");
  revalidatePath("/dashboard/stock");
}

export type InventorySessionSummary = InventorySessionRecord & {
  /** Products in the session, and how many have been counted. */
  totalCount: number;
  countedCount: number;
  varianceCount: number;
  varianceValue: number;
};

/** Session history for the list page, with each session's variance totals. */
export async function listInventorySessions(): Promise<InventorySessionSummary[]> {
  const user = await requireUser();

  const sessions = await prisma.inventorySession.findMany({
    where: { pharmacyId: user.pharmacyId },
    orderBy: { dateDebut: "desc" },
    include: {
      counts: {
        select: {
          quantiteTheorique: true,
          quantiteComptee: true,
          product: { select: { price: true } },
        },
      },
    },
  });

  return sessions.map((session) => {
    const varianceLines = session.counts.filter(
      (count) => count.quantiteComptee !== null && count.quantiteComptee !== count.quantiteTheorique,
    );
    return {
      ...toRecord(session),
      totalCount: session.counts.length,
      countedCount: session.counts.filter((count) => count.quantiteComptee !== null).length,
      varianceCount: varianceLines.length,
      varianceValue:
        Math.round(
          varianceLines.reduce(
            (sum, count) =>
              sum + (count.quantiteComptee! - count.quantiteTheorique) * Number(count.product.price),
            0,
          ) * 100,
        ) / 100,
    };
  });
}

function toRecord(session: {
  id: string;
  statut: string;
  dateDebut: Date;
  dateFin: Date | null;
}): InventorySessionRecord {
  return {
    id: session.id,
    statut: session.statut.toLowerCase() as InventorySessionStatus,
    dateDebut: session.dateDebut,
    dateFin: session.dateFin,
  };
}
